name: Novo Município
description: Sugerir um novo município para ser adicionado ao projeto
title: "[Novo spider]: Município-UF"
labels: ["type: spider"]
body:
  - type: input
    id: publishing-site
    attributes:
      label: URL da forma de consulta
      description: URL do site de publicação dos diários oficiais
    validations:
      required: true
  - type: input
    id: publishing-time
    attributes:
      label: Período de publicação
      description: Época de disponibilização dos diários no site
      placeholder: ex. mês/ano até atualmente; de 2016 à 2020
    validations:
      required: true
  - type: dropdown
    id: publication-format
    attributes:
      label: Formato da publicação
      multiple: false
      options:
        - Os diários oficiais são publicados em PDF (texto)
        - Os diários oficiais são publicados em PDF (imagem scanneada)
        - Os diários oficiais são publicados em outros formatos (ex. DOC, HTML, etc)
    validations:
      required: true
  - type: dropdown
    id: publication-details
    attributes:
      label: Conteúdo da publicação
      description: Selecione as opções que se aplicam
      multiple: true
      options:
        - "Diário único: documento publicado é uma edição completa do diário oficial"
        - "Diário agregado: documento publicado possui atos oficiais de outros municípios"
        - "Diário parcial: documento publicado é um pedaço do diário oficial do município"
  - type: dropdown
    id: website-details
    attributes:
      label: Detalhes do site de publicação
      description: Selecione as opções que se aplicam
      multiple: true
      options:
        - Possui paginação
        - Possui filtro por data
        - Possui captcha
  - type: textarea
    id: additional-information
    attributes:
      label: Observações
      description: Por favor, inclua qualquer informação relevante para o desenvolvimento do raspador. Uma informação especialmente relevante é se encontrou outros sites que publiquem diários deste município.
      placeholder: "Ex: existência de mais de um sistema de consulta, APIs, etc."
  - type: checkboxes
    id: terms
    attributes:
      label: Não existe uma issue aberta para esse município
      options:
        - label: Eu verifiquei que não existe uma issue aberta ou marcada com <a href='https://github.com/okfn-brasil/querido-diario/issues?q=label%3Aincompatible+is%3Aclosed'>*incompatible*</a> para o mesmo município.
          required: true
